on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows
    steps:
      - name: Send repo to Dataverse 
        uses: IQSS/dataverse-uploader@v1.6
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://darus.uni-stuttgart.de/dataverse/darus
          DATAVERSE_DATASET_DOI: doi.org/10.18419/DARUS-5297